name = "EnrichedFiniteElements"
uuid = "3055c13e-5365-4939-a1fc-ca14bc88bbd6"
authors = ["Kieran Quaine"]
version = "1.0.0-DEV"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.7.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
